name: 'Deploy to Aptible'
description: 'Deploy an App to Aptible'
inputs:
  username:
    description: 'Aptible username'
    required: True
  password:
    description: 'Aptible password'
    required: True
  environment:
    description: 'Aptible environment handle'
    required: True
  app:
    description: 'App handle'
    required: True
  type:
    description: 'Deploy strategy "git" or "deploy"'
    required: True
    default: 'git'
  git_remote:
    description: 'Aptible git remote domain'
    required: False
    default: primetime.aptible.com
  docker_img:
    description: 'Docker image'
    required: False
  private_registry_username:
    description: 'Private Registry Username'
    required: False
  private_registry_password:
    description: 'Private Registry Password'
    required: False
  config_variables:
    description: 'Configuration variables to set on deploy'
    required: False
  branch:
    description: 'Current branch checked out'
    required: False
    default: main
outputs:
   status:
    description: "The Success/Failure of the action"
runs:
  using: 'docker'
  # image: 'Dockerfile'
  image: docker://quay.io/aptible/aptible-deploy-action:v2
