name: 'Deploy to Aptible'
description: 'Deploy an App to Aptible'
inputs:
  username:
    description: 'Aptible username'
    required: True
  password:
    description: 'Aptible password'
    required: True
  environment:
    description: 'Aptible environment handle'
    required: True
  app:
    description: 'App handle'
    required: True
  type:
    description: 'Deploy strategy "git" or "docker"'
    required: True
    default: 'docker'
  git_remote:
    description: 'Aptible git remote domain'
    required: False
    default: primetime.aptible.com
  docker_img:
    description: 'Docker image'
    required: False
  private_registry_username:
    description: 'Private Registry Username'
    required: False
  private_registry_password:
    description: 'Private Registry Password'
    required: False
  config_variables:
    description: 'Configuration variables to set on deploy'
    required: False
  docker_repository_url:
    description: 'URL for docker image repository'
    required: False
  auth_root_url:
    description: 'Aptible Auth API endpoint'
    required: False
    default: https://auth.aptible.com
  api_root_url:
    description: 'Aptible Deploy API endpoint'
    required: False
    default: https://api.aptible.com
  aptible_remote:
    description: 'Aptible remote name'
    required: False
    default: aptible
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: 'docker'
  image: 'Dockerfile'
